[package]
name = "bevy-slime-sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.1"
bytemuck = "1.13.0"
rand = "0.8.5"
bevy-inspector-egui = "0.17.0"